# Generated by Django 4.2.10 on 2025-08-11 21:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='buyer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Buyer Profile',
                'verbose_name_plural': 'Buyer Profiles',
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='farmer_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='This is a denormalized field, managed by view. Set to null on account deletion.', max_length=20, null=True, unique=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('home_address', models.TextField(blank=True, null=True)),
                ('produce', models.JSONField(blank=True, default=list, help_text="List of produce items, e.g., ['Maize@10.50', 'Cassava@5.00']")),
                ('trust_level_stars', models.DecimalField(decimal_places=1, default=0.0, help_text='Calculated trust level in stars (0.0 to 5.0)', max_digits=3)),
                ('trust_score_percent', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated trust score in percentage (0.00 to 100.00)', max_digits=5)),
                ('is_discoverable_by_investors', models.BooleanField(default=True, help_text='If true, this farmer can be found by investors.')),
                ('total_income_last_12_months', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
            },
        ),
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='investor_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='This is a denormalized field, managed by view. Set to null on account deletion.', max_length=20, null=True, unique=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('total_invested_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_returns_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('investor_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investor Profile',
                'verbose_name_plural': 'Investor Profiles',
            },
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lender_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('country', models.CharField(default='Ghana', max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lender Profile',
                'verbose_name_plural': 'Lender Profiles',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_id', models.CharField(help_text='Unique ID from payment gateway', max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('recipient_or_sender', models.CharField(help_text='Name or number of the other party', max_length=255)),
                ('type', models.CharField(choices=[('sent', 'Sent'), ('received', 'Received')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('produce_sale', 'Produce Sale'), ('loan_repayment', 'Loan Repayment'), ('farm_input_purchase', 'Farm Input Purchase'), ('investment', 'Investment'), ('other', 'Other'), ('escrow_deposit', 'Escrow Deposit'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_party', models.ForeignKey(help_text='The account (Farmer/Investor/Lender/Buyer) whose transaction this is.', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(blank=True, help_text='The buyer account, if applicable (e.g., for produce sales).', limit_choices_to={'role': 'buyer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('related_order', models.ForeignKey(blank=True, help_text='The related Order, if this transaction is part of an order process.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_taken', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('date_repaid', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('repaid', 'Repaid'), ('defaulted', 'Defaulted'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('on_time', models.BooleanField(default=False, help_text='True if loan was repaid on or before due date.')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=5)),
                ('repayment_period_months', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True, help_text='True if loan is still outstanding or recently repaid.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='loans_taken', to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(limit_choices_to=models.Q(('role', 'investor'), ('role', 'platform_lender'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='loans_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-date_taken'],
            },
        ),
        migrations.CreateModel(
            name='InvestorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(limit_choices_to={'role': 'investor'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investor Review',
                'verbose_name_plural': 'Investor Reviews',
                'unique_together': {('investor', 'farmer')},
            },
        ),
    ]
