# Generated by Django 4.2.10 on 2025-08-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity ordered.', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount for the order, including any discounts.', max_digits=10)),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time the order was placed.')),
                ('delivery_date', models.DateField(blank=True, help_text='Expected or actual date of delivery.', null=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('paid_to_escrow', 'Paid to Escrow'), ('farmer_confirmed_delivery', 'Farmer Confirmed Delivery'), ('buyer_confirmed_receipt', 'Buyer Confirmed Receipt'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('resolved_to_farmer', 'Resolved (Funds to Farmer)'), ('resolved_to_buyer', 'Resolved (Funds to Buyer)'), ('resolved_split', 'Resolved (Funds Split)')], default='pending_payment', help_text='Current status of the order.', max_length=50)),
                ('is_paid', models.BooleanField(default=False, help_text='True if the buyer has paid the total_amount into escrow.')),
                ('is_delivered', models.BooleanField(default=False, help_text='True if the farmer has confirmed delivery.')),
                ('is_receipt_confirmed', models.BooleanField(default=False, help_text='True if the buyer has confirmed receipt of the produce.')),
                ('escrow_reference', models.CharField(blank=True, help_text='Unique reference for the escrow transaction.', max_length=255, null=True, unique=True)),
                ('is_disputed', models.BooleanField(default=False, help_text='True if there is an active dispute on this order.')),
                ('dispute_reason', models.CharField(blank=True, choices=[('quality_issue', 'Quality Issue'), ('quantity_mismatch', 'Quantity Mismatch'), ('late_delivery', 'Late Delivery'), ('no_delivery', 'No Delivery'), ('other', 'Other')], help_text='Reason for the dispute.', max_length=100, null=True)),
                ('dispute_details', models.TextField(blank=True, help_text='Detailed explanation of the dispute.', null=True)),
                ('dispute_raised_at', models.DateTimeField(blank=True, help_text='Timestamp when the dispute was raised.', null=True)),
                ('dispute_resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when the dispute was resolved.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The buyer who placed the order.', limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_orders', to=settings.AUTH_USER_MODEL)),
                ('dispute_raised_by', models.ForeignKey(blank=True, help_text='The account that raised the dispute.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(help_text='The farmer selling the produce.', limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('produce_listing', models.ForeignKey(blank=True, help_text='The produce listing associated with this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='marketplace.producelisting')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('escrow_deposit', 'Escrow Deposit'), ('escrow_release', 'Escrow Release'), ('escrow_refund', 'Escrow Refund'), ('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment'), ('dispute_resolution', 'Dispute Resolution')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('gateway_reference', models.CharField(blank=True, help_text='Reference ID from the payment gateway.', max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, help_text='The order associated with this payment transaction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_transactions', to='payments.order')),
                ('payer', models.ForeignKey(blank=True, help_text='The account initiating the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, help_text='The account receiving the payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Rating given by the buyer (1-5 stars).')),
                ('comment', models.TextField(blank=True, help_text='Optional comment from the buyer.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The buyer who gave the review.', limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(help_text='The farmer who received the review.', limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received_as_farmer', to=settings.AUTH_USER_MODEL)),
                ('order', models.OneToOneField(help_text='The specific order this review is for.', on_delete=django.db.models.deletion.CASCADE, related_name='buyer_review', to='payments.order')),
            ],
            options={
                'verbose_name': 'Buyer Review',
                'verbose_name_plural': 'Buyer Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('buyer', 'order')},
            },
        ),
    ]
