# Generated by Django 4.2.10 on 2025-08-12 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Unique ID from the USSD gateway for the session.', max_length=255, unique=True)),
                ('phone_number', models.CharField(help_text='Phone number of the USSD user.', max_length=20)),
                ('current_menu_state', models.CharField(default='initial_menu', help_text='Tracks which menu/step the user is currently on.', max_length=100)),
                ('previous_input', models.TextField(blank=True, help_text="Stores the user's input from the previous step.", null=True)),
                ('data_payload', models.JSONField(blank=True, default=dict, help_text='JSON field to store temporary session-specific data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='True if the session is ongoing, False if ended.')),
            ],
        ),
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_id', models.CharField(default=uuid.uuid4, help_text='Unique ID for the confirmation request.', max_length=255, unique=True)),
                ('request_type', models.CharField(choices=[('loan_offer', 'Loan Offer'), ('loan_repayment_confirm', 'Loan Repayment Confirmation'), ('produce_purchase_confirm', 'Produce Purchase Confirmation'), ('trust_view_request', 'Trust View Request')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, help_text='ID of the related core model object (e.g., Loan ID, Transaction ID).', null=True)),
                ('data_context', models.JSONField(blank=True, default=dict, help_text='Contextual data for the confirmation request.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='When this confirmation request expires.')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('initiator_account', models.ForeignKey(help_text='The Account (Farmer/Lender/Buyer) who initiated the confirmation request.', on_delete=django.db.models.deletion.CASCADE, related_name='initiated_confirmations', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(help_text='The Account (Farmer/Lender/Buyer) whose confirmation is awaited.', on_delete=django.db.models.deletion.CASCADE, related_name='pending_confirmations_for_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
