# Generated by Django 4.2.10 on 2025-08-11 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(help_text='The buyer participant in the conversation.', limit_choices_to={'role': 'buyer'}, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_conversations', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(help_text='The farmer participant in the conversation.', limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce_type', models.CharField(help_text='e.g., Maize, Tomatoes, Yam, Cocoa.', max_length=100)),
                ('quantity_available', models.DecimalField(decimal_places=2, help_text='Available quantity, e.g., 500.00 kg, 10.00 bags.', max_digits=10)),
                ('unit_of_measure', models.CharField(default='kg', help_text='e.g., kg, bags, crates, pieces.', max_length=20)),
                ('base_price_per_unit', models.DecimalField(decimal_places=2, help_text='Base price per unit, e.g., 2.50 GHS/kg.', max_digits=10)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Optional percentage discount (e.g., 10.00 for 10%).', max_digits=5, null=True)),
                ('discount_fixed_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fixed amount discount per unit (e.g., 0.50 GHS/kg).', max_digits=10, null=True)),
                ('location_description', models.CharField(help_text="e.g., 'Ashanti Region, Kumasi', 'Near Techiman market'.", max_length=255)),
                ('available_from', models.DateField(default=django.utils.timezone.localdate, help_text='Date from which the produce is available.')),
                ('available_until', models.DateField(blank=True, help_text='Date until which the produce is available. Null means ongoing.', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive'), ('expired', 'Expired'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('image_url', models.URLField(blank=True, help_text='URL to a photo of the produce.', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='The farmer offering the produce.', limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='produce_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Produce Listing',
                'verbose_name_plural': 'Produce Listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='The text content of the message.')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('read', 'Read')], default='sent', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(help_text='The conversation this message belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.conversation')),
                ('recipient', models.ForeignKey(help_text='The recipient of the message (farmer or buyer).', on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(help_text='The sender of the message (farmer or buyer).', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='related_listing',
            field=models.ForeignKey(blank=True, help_text='The produce listing that initiated this conversation (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='marketplace.producelisting'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('farmer', 'buyer', 'related_listing')},
        ),
    ]
