# Generated by Django 4.2.10 on 2025-08-11 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('investor', 'Investor'), ('admin', 'Admin'), ('platform_lender', 'Platform Lender'), ('buyer', 'Buyer')], default='farmer', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('pin', models.CharField(blank=True, help_text='4-digit PIN for USSD/mobile login', max_length=128, null=True)),
                ('receive_level_notifications', models.BooleanField(default=True, help_text='Receive notifications when your trust level changes.')),
                ('receive_sms_notifications', models.BooleanField(default=True, help_text='Receive notifications via SMS.')),
                ('receive_email_notifications', models.BooleanField(default=True, help_text='Receive notifications via Email.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.CheckConstraint(check=models.Q(('email__isnull', False), ('phone_number__isnull', False), _connector='OR'), name='email_or_phone_number_required', violation_error_message='Either email or phone number must be provided.'),
        ),
    ]
